# Generated by Django 5.0.14 on 2025-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('universe_id', models.AutoField(db_column='universe_id', primary_key=True, serialize=False)),
                ('universe_name', models.CharField(blank=True, db_column='universe_name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'universe',
                'managed': True,
            },
        ),
    ]
