# Generated by Django 5.0.14 on 2025-06-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('pilot_id', models.AutoField(db_column='pilot_id', primary_key=True, serialize=False)),
                ('pilot_name', models.CharField(blank=True, db_column='pilot_name', max_length=100, null=True)),
                ('pilot_vehicle', models.CharField(blank=True, db_column='pilot_vehicle', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pilot',
                'managed': True,
            },
        ),
    ]
