# Generated by Django 5.0.14 on 2025-07-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('pilot_id', models.AutoField(db_column='pilot_id', primary_key=True, serialize=False)),
                ('pilot_name', models.CharField(blank=True, db_column='pilot_name', max_length=100, null=True)),
                ('pilot_image', models.ImageField(blank=True, db_column='pilot_images', null=True, upload_to='pilot_images/')),
                ('pilot_vehicle', models.CharField(blank=True, db_column='pilot_vehicle', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('pilot_universe', models.ForeignKey(blank=True, db_column='pilot_universe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_in_universe', to='universe.universe')),
            ],
            options={
                'db_table': 'pilot',
                'managed': True,
            },
        ),
    ]
