# Generated by Django 5.0.14 on 2025-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_pilot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='pilot_image',
            field=models.ImageField(blank=True, db_column='pilot_images', null=True, upload_to='pilot_images/'),
        ),
    ]
