# Generated by Django 5.0.14 on 2025-06-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_pilot_pilot_image'),
        ('universe', '0002_universe_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='pilot_universe',
            field=models.ForeignKey(blank=True, db_column='pilot_universe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_in_universe', to='universe.universe'),
        ),
    ]
