# Generated by Django 5.0.14 on 2025-06-19 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        ('pilot', '0001_initial'),
        ('series', '0001_initial'),
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('model_id', models.AutoField(db_column='model_id', primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, db_column='model_name', max_length=100, null=True)),
                ('model_debut', models.CharField(blank=True, db_column='model_debut', max_length=200, null=True)),
                ('model_initial', models.CharField(blank=True, db_column='model_initial', max_length=100, null=True)),
                ('model_length', models.DecimalField(blank=True, db_column='model_length', decimal_places=2, max_digits=10, null=True)),
                ('model_width', models.DecimalField(blank=True, db_column='model_width', decimal_places=2, max_digits=10, null=True)),
                ('model_height', models.DecimalField(blank=True, db_column='model_height', decimal_places=2, max_digits=10, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('model_grade', models.ForeignKey(blank=True, db_column='model_grade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.grade')),
            ],
            options={
                'db_table': 'model_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelPilotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='gundam_data.modeldata')),
                ('pilot', models.ForeignKey(db_column='pilot_id', on_delete=django.db.models.deletion.CASCADE, to='pilot.pilot')),
            ],
            options={
                'db_table': 'model_pilot_assignment',
                'managed': True,
                'unique_together': {('model', 'pilot')},
            },
        ),
        migrations.CreateModel(
            name='ModelSeriesOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='gundam_data.modeldata')),
                ('series', models.ForeignKey(db_column='series_id', on_delete=django.db.models.deletion.CASCADE, to='series.series')),
            ],
            options={
                'db_table': 'model_series_occurrence',
                'managed': True,
                'unique_together': {('model', 'series')},
            },
        ),
        migrations.CreateModel(
            name='ModelUniverseOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='gundam_data.modeldata')),
                ('universe', models.ForeignKey(db_column='universe_id', on_delete=django.db.models.deletion.CASCADE, to='universe.universe')),
            ],
            options={
                'db_table': 'model_universe_occurrence',
                'managed': True,
                'unique_together': {('model', 'universe')},
            },
        ),
    ]
