# Generated by Django 5.0.14 on 2025-07-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gundam_data', '0001_initial'),
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpilotassignment',
            name='pilot',
            field=models.ForeignKey(db_column='pilot_id', on_delete=django.db.models.deletion.CASCADE, to='pilot.pilot'),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='pilots',
            field=models.ManyToManyField(db_column='model_pilots', related_name='models_piloted', through='gundam_data.ModelPilotAssignment', to='pilot.pilot'),
        ),
        migrations.AddField(
            model_name='modelseriesoccurrence',
            name='model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='gundam_data.modeldata'),
        ),
    ]
