# Generated by Django 5.0.14 on 2025-06-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gundam_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('types_id', models.AutoField(db_column='types_id', primary_key=True, serialize=False)),
                ('types_name', models.CharField(blank=True, db_column='types_name', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(db_column='vendor_id', primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, db_column='vendor_name', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='modeldata',
            name='model_debut',
        ),
        migrations.AddField(
            model_name='modeldata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
