# Generated by Django 5.0.14 on 2025-07-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gundam_data', '0002_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelseriesoccurrence',
            name='series',
            field=models.ForeignKey(db_column='series_id', on_delete=django.db.models.deletion.CASCADE, to='series.series'),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='model_seller',
            field=models.ForeignKey(blank=True, db_column='model_seller', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gundam_data.seller'),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='model_type',
            field=models.ForeignKey(blank=True, db_column='model_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gundam_data.types'),
        ),
        migrations.AlterUniqueTogether(
            name='modelpilotassignment',
            unique_together={('model', 'pilot')},
        ),
        migrations.AlterUniqueTogether(
            name='modelseriesoccurrence',
            unique_together={('model', 'series')},
        ),
    ]
