# Generated by Django 5.0.14 on 2025-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gundam_data', '0002_types_vendor_remove_modeldata_model_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='model_image',
            field=models.ImageField(blank=True, db_column='model_image', null=True, upload_to='model_images/'),
        ),
    ]
