# Generated by Django 5.0.14 on 2025-07-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('gundam_data', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldata',
            name='model_grade',
            field=models.ForeignKey(blank=True, db_column='model_grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_in_grade', to='grade.grade'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='model_seller',
            field=models.ForeignKey(blank=True, db_column='model_seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_in_seller', to='gundam_data.seller'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='model_type',
            field=models.ForeignKey(blank=True, db_column='model_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_in_type', to='gundam_data.types'),
        ),
    ]
