# Generated by Django 5.0.14 on 2025-07-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gundam_data', '0003_modeldata_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldata',
            name='model_image',
        ),
        migrations.AddField(
            model_name='modeldata',
            name='model_type',
            field=models.ForeignKey(blank=True, db_column='model_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gundam_data.types'),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='model_vendor',
            field=models.ForeignKey(blank=True, db_column='model_vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gundam_data.vendor'),
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='model_photos/')),
                ('is_main', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('model_data', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gundam_data.modeldata')),
            ],
            options={
                'db_table': 'model_image',
                'ordering': ['is_main', '-create_date'],
                'managed': True,
            },
        ),
    ]
