# Generated by Django 5.0.14 on 2025-07-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(db_column='series_id', primary_key=True, serialize=False)),
                ('series_name', models.CharField(blank=True, db_column='series_name', max_length=100)),
                ('series_image', models.ImageField(blank=True, db_column='series_image', null=True, upload_to='series_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('series_universe', models.ForeignKey(blank=True, db_column='series_universe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_in_universe', to='universe.universe')),
            ],
            options={
                'db_table': 'series',
                'managed': True,
            },
        ),
    ]
