# Generated by Django 5.0.14 on 2025-06-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('universe', '0002_universe_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_universe',
            field=models.ForeignKey(blank=True, db_column='series_universe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_in_universe', to='universe.universe'),
        ),
    ]
