# Generated by Django 5.0.14 on 2025-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_is_active_alter_series_series_universe'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_image',
            field=models.ImageField(blank=True, db_column='series_image', null=True, upload_to='series_logos/'),
        ),
    ]
